services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - user-service
      - product-service
    environment:
      - CONFIG_PATH=configs/gateway.yaml

  user-service:
    build: ./services/user-service
    ports:
      - "8081:8081"

  product-service:
    build: ./services/product-service
    ports:
      - "8082:8082"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  mongo_data:
